apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeliveryCharge
  labels:
    app: DeliveryCharge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DeliveryCharge
  template:
    metadata:
      labels:
        app: DeliveryCharge
    spec:
      containers:
        - name: DeliveryCharge
          image: 879772956301.dkr.ecr.ap-northeast-1.amazonaws.com/ezdelivery-deliverycharge:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5