apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm
  namespace: ezdelivery
  labels:
    app: alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm
  template:
    metadata:
      labels:
        app: alarm
    spec:
      containers:
        - name: alarm
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user08-ezdelivery-alarm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: alarm.prefix
              valueFrom:
                configMapKeyRef:
                  name: ezdelivery-config
                  key: alarm.prefix
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: alarm
  namespace: ezdelivery
  labels:
    app: alarm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: alarm
