apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ezdelivery
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/ezdelivery-order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.url.payment
              valueFrom:
                configMapKeyRef:
                  name: ezdelivery-config
                  key: api.url.payment

---

apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: ezdelivery
  labels:
    app: order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order
